name: Build ZMK-Firmware
  
on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    steps:
      - name: Build Firmware
        id: build_firmware
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
      - name: File structure
        id: file_structure
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "build/artifacts/firmware"
