name: Build ZMK-Firmware
  
on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: File structure
        id: file_structure
        run: |
          ls ${{ github.workspace }}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "build/artifacts/firmware"
