name: Create Release

on:
  workflow_run:
    workflows: [Build ZMK-Firmware]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "build/artifacts/firmware"
